### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Dovahkiin1991** [Dovahkiin1991/homepage-old#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Dovahkiin1991** [comment]
Some test comment :)

**Comment by AlexUlych** [comment]
Ok, watching :)

**Comment by Dovahkiin1991** [comment]
Hey, my name is Sasha and I can help you with converting design to HTML. In my work, I use scss+gulp, and git for commits. For responsive I usually use bootstrap as the grid, but can work with others too. I do quality work.
